const INDEX_ROUTE = "/";

const API_ROUTE = `${INDEX_ROUTE}api`;
const API_GET_ENTRIES_ROUTE = `${API_ROUTE}/entries`;
const API_GET_ENTRY_ROUTE = `${API_GET_ENTRIES_ROUTE}/:uuid`;

const API_POST_ENTRY_ROUTE = `${API_ROUTE}/entries`;
const API_POST_V2_ENTRY_ROUTE = `${API_ROUTE}/v2/entries`;
const API_PUT_ENTRY_ROUTE = `${API_ROUTE}/entries/:uuid`;
const API_PUT_V2_ENTRY_ROUTE = `${API_ROUTE}/v2/entries/:uuid`;
const API_DELETE_ENTRY_ROUTE = `${API_ROUTE}/entries/:uuid`;
const API_PATCH_ENTRIES_ROUTE = `${API_ROUTE}/entries`;

const API_GET_ANIMALS_ROUTE = `${API_ROUTE}/animals`;

const API = {
  INDEX_ROUTE: INDEX_ROUTE,
  API_ROUTE: API_ROUTE,
  API_GET_ENTRIES_ROUTE: API_GET_ENTRIES_ROUTE,
  API_GET_ENTRY_ROUTE: API_GET_ENTRY_ROUTE,
  API_POST_ENTRY_ROUTE: API_POST_ENTRY_ROUTE,
  API_POST_V2_ENTRY_ROUTE: API_POST_V2_ENTRY_ROUTE,
  API_PUT_ENTRY_ROUTE: API_PUT_ENTRY_ROUTE,
  API_PUT_V2_ENTRY_ROUTE: API_PUT_V2_ENTRY_ROUTE,
  API_DELETE_ENTRY_ROUTE: API_DELETE_ENTRY_ROUTE,
  API_PATCH_ENTRIES_ROUTE: API_PATCH_ENTRIES_ROUTE,
  API_GET_ANIMALS_ROUTE: API_GET_ANIMALS_ROUTE,
};

module.exports = API;
